/* JS */ gapi.loaded_3(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Qr;Qr=function(a){return(a=a.exec(_.wb))?a[1]:""};_.Rr=function(){if(_.Yg)return Qr(/Firefox\/([0-9.]+)/);if(_.rc||_.sc||_.qc)return _.Mc;if(_.bh)return _.mc()?Qr(/CriOS\/([0-9.]+)/):Qr(/Chrome\/([0-9.]+)/);if(_.ch&&!_.mc())return Qr(/Version\/([0-9.]+)/);if(_.Zg||_.$g){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.wb);if(a)return a[1]+"."+a[2]}else if(_.ah)return(a=Qr(/Android\s+([0-9.]+)/))?a:Qr(/Version\/([0-9.]+)/);return""}();

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Vr;_.Sr=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};_.h=_.Sr.prototype;_.h.clone=function(){return new _.Sr(this.left,this.top,this.width,this.height)};_.h.WA=_.ea(27);_.h.intersects=function(a){return this.left<=a.left+a.width&&a.left<=this.left+this.width&&this.top<=a.top+a.height&&a.top<=this.top+this.height};
_.h.contains=function(a){return a instanceof _.Fq?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};_.h.distance=function(a){var b=a.x<this.left?this.left-a.x:Math.max(a.x-(this.left+this.width),0);a=a.y<this.top?this.top-a.y:Math.max(a.y-(this.top+this.height),0);return Math.sqrt(b*b+a*a)};_.h.nn=function(){return new _.Gq(this.width,this.height)};
_.h.getCenter=function(){return new _.Fq(this.left+this.width/2,this.top+this.height/2)};_.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};_.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
_.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.h.translate=function(a,b){a instanceof _.Fq?(this.left+=a.x,this.top+=a.y):(this.left+=a,"number"===typeof b&&(this.top+=b));return this};_.h.scale=function(a,b){b="number"===typeof b?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};_.Tr=function(a){return _.vr(a,"position")};
_.Ur=function(a,b){a=a.style;"opacity"in a?a.opacity=b:"MozOpacity"in a?a.MozOpacity=b:"filter"in a&&(a.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")};Vr=function(a,b){return(b=_.ur(a,b))?_.Nr(a,b):0};_.Wr=function(a,b){if(_.rc){var c=Vr(a,b+"Left"),d=Vr(a,b+"Right"),e=Vr(a,b+"Top");a=Vr(a,b+"Bottom");return new _.pr(e,d,a,c)}c=_.tr(a,b+"Left");d=_.tr(a,b+"Right");e=_.tr(a,b+"Top");a=_.tr(a,b+"Bottom");return new _.pr(parseFloat(e),parseFloat(d),parseFloat(a),parseFloat(c))};
_.Xr=function(){if(_.yc){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(_.wb))?a[1]:"0"}return _.xc?(a=/10[_.][0-9_.]+/,(a=a.exec(_.wb))?a[0].replace(/_/g,"."):"10"):_.Ac?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(_.wb))?a[1]:""):_.Bc||_.Cc||_.Fc?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(_.wb))?a[1].replace(/_/g,"."):""):""}();

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Yr,Zr,bs;_.Sr.prototype.WA=_.Tc(27,function(a){var b=Math.max(this.left,a.left),c=Math.min(this.left+this.width,a.left+a.width);if(b<=c){var d=Math.max(this.top,a.top);a=Math.min(this.top+this.height,a.top+a.height);d<=a&&(this.left=b,this.top=d,this.width=c-b,this.height=a-d)}});Yr=function(a,b){return new _.Fq(a.x-b.x,a.y-b.y)};
Zr=function(a){if(_.rc&&!_.Qc(8))return a.offsetParent;var b=_.Md(a),c=_.vr(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=_.vr(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null};
_.$r=function(a){for(var b=new _.pr(0,Infinity,Infinity,0),c=_.Nd(a),d=c.vb().body,e=c.vb().documentElement,f=_.Kq(c.tb);a=Zr(a);)if(!(_.rc&&0==a.clientWidth||_.vc&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=_.vr(a,"overflow")){var g=_.zr(a),k=new _.Fq(a.clientLeft,a.clientTop);g.x+=k.x;g.y+=k.y;b.top=Math.max(b.top,g.y);b.right=Math.min(b.right,g.x+a.clientWidth);b.bottom=Math.min(b.bottom,g.y+a.clientHeight);b.left=Math.max(b.left,g.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);
b.top=Math.max(b.top,f);c=_.Jq(c.Ab());b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null};_.as=function(a){var b=_.zr(a);a=_.Gr(a);return new _.Sr(b.x,b.y,a.width,a.height)};bs=function(a,b){return(b&8&&_.Lr(a)?b^4:b)&-9};
_.hs=function(a,b,c,d,e,f,g,k,l){var m;if(m=c.offsetParent){var n="HTML"==m.tagName||"BODY"==m.tagName;if(!n||"static"!=_.Tr(m)){var p=_.zr(m);if(!n){n=_.Lr(m);var u;if(u=n){u=_.ch&&0<=_.vb(_.Rr,10);var r=_.Gc&&0<=_.vb(_.Xr,10),v=_.bh&&0<=_.vb(_.Rr,85);u=_.uc||u||r||v}n=u?-m.scrollLeft:!n||_.tc&&_.Oc("8")||"visible"==_.vr(m,"overflowX")?m.scrollLeft:m.scrollWidth-m.clientWidth-m.scrollLeft;p=Yr(p,new _.Fq(n,m.scrollTop))}}}m=p||new _.Fq;p=_.as(a);(n=_.$r(a))&&p.WA(new _.Sr(n.left,n.top,n.right-n.left,
n.bottom-n.top));n=_.Nd(a);r=_.Nd(c);n.vb()!=r.vb()&&(u=n.vb().body,r=_.Er(u,r.Ab()),r=Yr(r,_.zr(u)),!_.rc||_.Qc(9)||_.Hq(n.tb)||(r=Yr(r,_.Lq(n.tb))),p.left+=r.x,p.top+=r.y);a=bs(a,b);b=p.left;a&4?b+=p.width:a&2&&(b+=p.width/2);b=new _.Fq(b,p.top+(a&1?p.height:0));b=Yr(b,m);e&&(b.x+=(a&4?-1:1)*e.x,b.y+=(a&1?-1:1)*e.y);if(g)if(l)var t=l;else if(t=_.$r(c))t.top-=m.y,t.right-=m.x,t.bottom-=m.y,t.left-=m.x;e=t;l=b.clone();t=bs(c,d);d=_.Gr(c);a=k?k.clone():d.clone();k=l;l=a;k=k.clone();l=l.clone();a=0;
if(f||0!=t)t&4?k.x-=l.width+(f?f.right:0):t&2?k.x-=l.width/2:f&&(k.x+=f.left),t&1?k.y-=l.height+(f?f.bottom:0):f&&(k.y+=f.top);g&&(e?(f=k,t=l,a=0,65==(g&65)&&(f.x<e.left||f.x>=e.right)&&(g&=-2),132==(g&132)&&(f.y<e.top||f.y>=e.bottom)&&(g&=-5),f.x<e.left&&g&1&&(f.x=e.left,a|=1),g&16&&(b=f.x,f.x<e.left&&(f.x=e.left,a|=4),f.x+t.width>e.right&&(t.width=Math.min(e.right-f.x,b+t.width-e.left),t.width=Math.max(t.width,0),a|=4)),f.x+t.width>e.right&&g&1&&(f.x=Math.max(e.right-t.width,e.left),a|=1),g&2&&
(a|=(f.x<e.left?16:0)|(f.x+t.width>e.right?32:0)),f.y<e.top&&g&4&&(f.y=e.top,a|=2),g&32&&(b=f.y,f.y<e.top&&(f.y=e.top,a|=8),f.y+t.height>e.bottom&&(t.height=Math.min(e.bottom-f.y,b+t.height-e.top),t.height=Math.max(t.height,0),a|=8)),f.y+t.height>e.bottom&&g&4&&(f.y=Math.max(e.bottom-t.height,e.top),a|=2),g&8&&(a|=(f.y<e.top?64:0)|(f.y+t.height>e.bottom?128:0)),g=a):g=256,a=g);f=new _.Sr(0,0,0,0);f.left=k.x;f.top=k.y;f.width=l.width;f.height=l.height;g=a;g&496||(_.xr(c,new _.Fq(f.left,f.top)),a=f.nn(),
d==a||d&&a&&d.width==a.width&&d.height==a.height||(f=a,d=_.Hq(_.Nd(_.Md(c)).tb),!_.rc||_.Oc("10")||d&&_.Oc("8")?(c=c.style,_.uc?c.MozBoxSizing="border-box":_.vc?c.WebkitBoxSizing="border-box":c.boxSizing="border-box",c.width=Math.max(f.width,0)+"px",c.height=Math.max(f.height,0)+"px"):(k=c.style,d?(d=_.Wr(c,"padding"),c=_.Ar(c),k.pixelWidth=f.width-c.left-d.left-d.right-c.right,k.pixelHeight=f.height-c.top-d.top-d.bottom-c.bottom):(k.pixelWidth=f.width,k.pixelHeight=f.height))));return g};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ms;ms=function(a,b){a&&(a=a.parentNode);for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};_.ns=function(a){if(1==a.nodeType)return _.Dr(a);a=a.changedTouches?a.changedTouches[0]:a;return new _.Fq(a.clientX,a.clientY)};
if("undefined"===typeof os)var os={};_.ps=function(a){this.ka=a;this.ua=a.kc()};_.ps.prototype.Yq=function(){qs(this)};
var qs=function(a){var b=a.ka.Oc();if(a.ua.anchorBox&&b&&b.Ma())b=_.zr(b.Ma()),a.ua.anchorBox.left+=b.x,a.ua.anchorBox.top+=b.y;else{b=a.ua.anchor;if("_default"!=b&&"_iframe"!=b){var c=_.Od(document,b);if(c)a.ua.anchorBox=_.as(c);else{_.Df("Anchor not found in DOM: "+b+'. Falling back to "_default".');a.ua.anchor="_default";return}}"_iframe"==b&&(b=_.Jq(),a.ua.anchorBox=new _.Sr(0,0,b.width,b.height))}a.ua.anchor=""};_.ps.prototype.onBeforeParentOpen=_.ps.prototype.Yq;
_.rs=function(a){_.ps.call(this,a)};_.fi(_.rs,_.ps);_.h=_.rs.prototype;_.h.open=function(){var a=this.ua,b=document.createElement("ins");document.getElementById(a.container).appendChild(b);b.style.display="block";_.rr(b,a.containerCss);this.ka.Lf(b);this.ka.lg(b)};_.h.yd=function(){document.getElementById(this.ka.id).style.height=this.ka.height+"px"};_.h.close=function(){_.be(this.ka.Bb());_.be(this.yg);this.yg=null};_.h.gw=_.ea(15);
_.h.Ah=function(){if(this.yg)return this.yg;var a=this.ua;!a.anchorBox&&a.anchor&&qs(this);var b=this.ka.Oc();if("_default"==a.anchor&&b){var c=_.as(_.Od(document,b.Bb()));a.anchorBox=c}if(!a.anchorBox)return _.Df("No anchor box defined."),null;a=new _.Fq(a.anchorBox.left,a.anchorBox.top);b&&(b=_.Er(b.Ma(),window),this.Yl=new _.Fq,this.Yl.x=b.x,this.Yl.y=b.y,a.x+=b.x,a.y+=b.y,_.ss(a));this.Hx=a;b=_.ts(this,!0);this.yg=document.createElement("ins");this.yg.style.cssText=b;document.body.appendChild(this.yg);
return this.yg};_.ts=function(a,b){var c=a.ua;return"position: absolute !important;background-color: transparent !important;left: "+a.Hx.x+"px !important;top: "+a.Hx.y+"px !important;width: "+c.anchorBox.width+"px !important;height: "+c.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(b?"block":"none")+" !important;"};
_.us=function(a,b){var c=0,d=0;if(b.pageX||b.pageY)c=b.pageX,d=b.pageY;else if(b.clientX||b.clientY)c=b.target?b.target:b.srcElement,d=c.ownerDocument&&c.ownerDocument.parentWindow?c.ownerDocument.parentWindow:window,_.rc?(c=d.document.documentElement.scrollLeft,d=d.document.documentElement.scrollTop):(c=d.pageXOffset,d=d.pageYOffset),c=b.clientX+c,d=b.clientY+d;b=new _.Fq(c,d);a=_.as(a);return a=new _.pr(a.top,a.left+a.width,a.top+a.height,a.left),a.contains(b)};
_.ss=function(a){var b=window,c=document.body,d=_.zr(c);b=c.currentStyle||b.getComputedStyle(c,"");b.position&&"static"!=b.position&&(a.x-=d.x,a.y-=d.y)};_.vs=function(a){var b=a.ka.Oc()&&a.ka.Oc().Bb();b=b&&b.style.zIndex?parseInt(b.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.ua.zIndex||b))};
var ws,xs,ys;ws={"bottom-center":1,"bottom-end":13,"bottom-left":1,"bottom-right":5,"bottom-start":9,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":5,"right-center":4,"right-top":4,"top-center":0,"top-end":12,"top-left":0,"top-right":4,"top-start":8};xs={"bottom-center":!0,"top-center":!0};ys={"left-center":!0,"right-center":!0};
_.zs=function(a,b,c,d,e){e=e||{x:0,y:0};if(xs[b]){var f=_.Gr(a).width/2;e.x="top-right"==d||"bottom-right"==d?e.x+f:e.x-f}xs[d]&&(f=_.Gr(c).width/2,e.x+=f);ys[b]&&(f=_.Gr(a).height/2,e.y="right-bottom"==d||"left-bottom"==d?e.y+f:e.y-f);ys[d]&&(e.y+=_.Gr(c).height/2);_.hs(c,ws[d],a,ws[b],new _.Fq(e.x,e.y));d=ms(a,function(g){if(g==document)return!1;g=_.Tr(g);return!!g&&"static"!=g});c=b=0;d&&(c=_.zr(d),b=-c.x,c=-c.y);a=a.style;parseInt(a.left,10)<b&&(a.left=b+"px");parseInt(a.top,10)<c&&(a.top=c+"px")};
_.As=function(a){_.ps.call(this,a.ka);this.ng=a;this.by=[]};_.fi(_.As,_.rs);_.h=_.As.prototype;_.h.Yq=function(){this.ng.Yq()};_.h.open=function(){this.ng.open();(this.ua.closeClickDetection||this.ua.hideClickDetection)&&Bs(this)};_.h.yd=function(a){this.ng.yd(a)};_.h.dK=function(a){this.ng.onRenderStart&&this.ng.onRenderStart(a)};_.h.close=function(){if(this.ua.closeClickDetection||this.ua.hideClickDetection)_.nb(this.by,function(a){_.Si(a)}),this.by=[];this.ng.close()};
var Bs=function(a){_.nb(["click","touchstart"],(0,_.R)(function(b){this.by.push(_.Li(document,b,(0,_.R)(this.OQ,this),!0))},a))};_.As.prototype.OQ=function(a){_.us(this.ka.Bb(),a)||(this.ua.hideClickDetection&&this.ng.show?this.ng.show(!1):this.close())};_.As.prototype.onBeforeParentOpen=_.As.prototype.Yq;_.As.prototype.open=_.As.prototype.open;_.As.prototype.onready=_.As.prototype.yd;_.As.prototype.onRenderStart=_.As.prototype.dK;_.As.prototype.close=_.As.prototype.close;

var XT,ZT,$T;for(_.WT=function(a){return{kc:function(){return a},Oc:function(){return a.openerIframe}}},XT=function(a){(new _.ps(_.WT(a))).Yq()},ZT="bubble circlepicker float hover hover-menu slide-menu".split(" "),$T=0;$T<ZT.length;$T++)_.hm[ZT[$T]]=XT;

_.sG=function(a){_.ps.call(this,a.ka);this.ng=a;this.Dp=null};_.fi(_.sG,_.rs);_.sG.prototype.open=function(){this.ua.targetPos=this.ua.targetPos||"top-start";this.ua.anchorPos=this.ua.anchorPos||"bottom-start";var a=this.Ah(),b=this.ka.Bb();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.ng.open()};
_.sG.prototype.yd=function(){if(this.ua.closeClickDetection){var a=this,b=function(e){_.us(a.ka.Bb(),e)||(a.ka.close(),a.Dp=null)};document.yQ?(document.yQ("click",b),this.Dp=function(){document.removeEventListener("click",b,!1)}):document.attachEvent&&(document.attachEvent("onclick",b),this.Dp=function(){document.detachEvent("onclick",b)})}var c=document.getElementById(this.ka.id),d=this.ka.Bb();c.style.height=this.ka.height+"px";(c=this.Ah())&&_.zs(d,this.ua.targetPos,c,this.ua.anchorPos,{x:this.ua.leftOffset||
0,y:this.ua.topOffset||0});d.style.visibility="visible"};_.sG.prototype.close=function(){this.ng.close();this.Dp&&this.Dp()};_.sG.prototype.open=_.sG.prototype.open;_.sG.prototype.onready=_.sG.prototype.yd;_.sG.prototype.close=_.sG.prototype.close;
_.tG=function(a){_.ps.call(this,a)};_.fi(_.tG,_.rs);_.h=_.tG.prototype;_.h.create=function(a){this.Ja=document.createElement("div");var b={position:"absolute",top:"-10000px",zIndex:_.vs(this)};this.ua.width&&(b.width=this.ua.width+"px");for(var c in b)this.Ja.style[c]=b[c];(a||document.body).appendChild(this.Ja)};_.h.open=function(a){this.ka.Pg("updateContainer",(0,_.R)(this.xj,this));this.create(a);this.ka.lg(this.Ja);this.ka.Lf(this.Ja)};
_.h.yd=function(){var a=uG(this);if(a){var b=document.getElementById(this.ka.ma());b.style.height=a.height+"px";b.style.width=a.width+"px";this.ka.width=a.width;this.ka.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};_.h.close=function(){this.Ja.parentNode&&this.Ja.parentNode.removeChild(this.Ja)};
_.h.xj=function(a,b,c){var d=this.ka.Bb();d&&(a?(this.$g(b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.R)(function(){vG(d,!0);d.style.opacity=1},this),0)):(d.style.display="none",vG(d,!1),d.style.opacity=0))};var vG=function(a,b){for(var c=0;c<wG.length;c++)a.style[wG[c]]=b?"opacity .13s linear":""};
_.tG.prototype.$g=function(a,b){var c=this.ka.Oc();a+=10;b+=10;if(_.q.util&&(c&&(c=_.Er(c.Bb(),window),a+=c.x,b+=c.y),c=uG(this))){var d=_.Jq(window),e=_.Lq(document);if(d.width&&(a=Math.min(a,d.width+e.x-c.width-8),b+c.height>d.height+e.y-8)){b-=20+c.height;var f=window,g=f.document;d=0;if(g){d=g.body;var k=g.documentElement;if(k&&d)if(f=_.Iq(f).height,_.Hq(g)&&k.scrollHeight)d=k.scrollHeight!=f?k.scrollHeight:k.offsetHeight;else{g=k.scrollHeight;var l=k.offsetHeight;k.clientHeight!=l&&(g=d.scrollHeight,
l=d.offsetHeight);d=g>f?g>l?g:l:g<l?g:l}else d=0}b=Math.max(b,Math.min(e.y+1,d-c.height))}}c=this.ka.Bb();c.style.left=a+"px";c.style.top=b+"px"};var uG=function(a){return a.ka.width&&a.ka.height?{width:a.ka.width,height:a.ka.height}:(a=a.ka.Ma())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null},wG=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.tG.prototype.open=_.tG.prototype.open;_.tG.prototype.onready=_.tG.prototype.yd;
_.tG.prototype.close=_.tG.prototype.close;
_.xG=function(a){_.ps.call(this,a)};_.fi(_.xG,_.rs);_.xG.prototype.open=function(){var a=document.createElement("div");_.rr(a,{top:"-10000px",position:"absolute",zIndex:_.vs(this)});this.Ah().parentNode.appendChild(a);this.ka.Lf(a);this.ka.lg(a)};
_.xG.prototype.yd=function(){var a=document.getElementById(this.ka.id);a.style.height=this.ka.height+"px";a.style.width=this.ka.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.ka.Bb();b.style.lineHeight=0;var c=this.Ah(),d=this.ua.targetPos||"top-start",e=this.ua.anchorPos||"bottom-start",f=this.ua.leftOffset||0,g=this.ua.topOffset||0;_.zs(b,d,c,e,{x:f,y:g});var k=_.Jq(window),l=_.Lq(document),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x;k=b.offsetTop<l.y||b.offsetTop+
b.offsetHeight>k.height+l.y;d=yG(d,m,k);e=yG(e,m,k);_.zs(b,d,c,e,{x:f*(m?-1:1),y:g*(k?-1:1)});b.style.visibility="visible";this.nv=_.Li(document,"mouseover",(0,_.R)(function(n){n.target===a&&this.dl&&(window.clearTimeout(this.dl),this.dl=null)},this));this.GB=_.Li(document,"mouseout",(0,_.R)(function(n){n.target===a&&(this.dl=window.setTimeout((0,_.R)(this.ka.close,this.ka),1E3))},this))};
var yG=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&zG[a[d]]&&(a[d]=zG[a[d]]),c&&AG[a[d]]&&(a[d]=AG[a[d]]);return a.join("-")};_.xG.prototype.close=function(){this.nv&&(_.Si(this.nv),_.Si(this.GB),this.GB=this.nv=null);this.dl&&(window.clearTimeout(this.dl),this.dl=null);_.rs.prototype.close.call(this)};_.xG.prototype.nv=null;_.xG.prototype.GB=null;_.xG.prototype.dl=null;var zG={end:"start",left:"right",right:"left",start:"end"},AG={top:"bottom",bottom:"top"};_.xG.prototype.open=_.xG.prototype.open;
_.xG.prototype.onready=_.xG.prototype.yd;_.xG.prototype.close=_.xG.prototype.close;

_.gm.hover=function(a){var b=new _.tG(_.WT(a));b.create(a.where);a.where=b.Ja;a.onClose=function(){b.close()};a.onRestyle=function(c){if(c.updateContainer){var d=c.updateContainer;b.xj(d.visible,d.x,d.y)}c.width&&(b.ka.width=c.width);c.height&&(b.ka.height=c.height)};a.onCreate=function(c){b.ka=c;c.Oc=function(){return a.openerIframe};c.register("_ready",(0,_.R)(b.yd,b),_.ym);c.updateContainer=function(d,e,f){b.xj(d,e,f)}}};

var oP=function(a,b){this.Uc=a;this.Re=b};oP.prototype.yv=function(a){this.Uc.or(this.Re,a)};oP.prototype.er=function(){this.Uc.oh(this.Re)};oP.prototype.vv=function(){this.Uc.oc(this.Re)};oP.prototype.maa=function(a,b,c,d,e){this.Uc.oe(this.Re,a,b,c,d,e)};
_.pP=function(a){this.w=this.Db=a;this.n=null;this.slf=0;this.ssh=!1;this.sen=!0;this.shl=this.itm=null};_.pP.prototype.sm=function(a,b){this.Db.to(new oP(a,this));this.n=b};_.pP.prototype.sh=function(){this.Db.show()};_.pP.prototype.hi=function(){this.Db.mc()};_.pP.prototype.cl=function(){this.Db.close()};_.pP.prototype.en=function(){this.Db.enable()};_.pP.prototype.di=function(){this.Db.disable()};_.pP.prototype.hl=function(a){this.Db.PS(a)};_.pP.prototype.vr=function(a,b){this.Db.IT(a,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.lU=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};_.mU=!_.rc&&!_.Wg();

var $V=function(a){a.Uc.os(a.Re)},aW=function(a){this.Re=a;this.Ge=0;this.Nr=!1;this.EG=!0;this.Mk=null},bW=function(a){return 5==a.Ge||4==a.Ge};aW.prototype.isEnabled=function(){return this.EG};aW.prototype.Ic=function(a){this.EG=a};
var cW=function(a,b,c){this.Rv=a||{};this.SA=b||0;this.JV=c||0;a={};b=(0,_.R)(this.nH,this);a.fc=b;b=(0,_.R)(this.mC,this);a.rc=b;b=(0,_.R)(this.sD,this);a.sc=b;b=(0,_.R)(this.Bq,this);a.hc=b;b=(0,_.R)(this.wp,this);a.cc=b;b=(0,_.R)(this.fI,this);a.os=b;b=(0,_.R)(this.eI,this);a.or=b;b=(0,_.R)(this.cI,this);a.oh=b;b=(0,_.R)(this.aI,this);a.oc=b;b=(0,_.R)(this.bI,this);a.oe=b;b=(0,_.R)(this.dI,this);a.oi=b;this.Uc=a};_.h=cW.prototype;
_.h.mC=function(a,b,c){try{a+=null!=b?"_"+b:"",c.sm(this.Uc,a),this.Rv[a]=new aW(c)}catch(d){return!1}return!0};_.h.nH=function(a,b){return(a=this.Rv[a+(null!=b?"_"+b:"")])?a.Re:null};_.h.sD=function(a){var b=dW(this,a);if(b&&(2==b.Ge||3==b.Ge)&&b.isEnabled()&&!b.Nr){try{a.sh()}catch(c){}b.Nr=!0}};_.h.Bq=function(a){var b=dW(this,a);if(b&&(2==b.Ge||3==b.Ge||bW(b))&&b.Nr){try{a.hi()}catch(c){}b.Nr=!1}};_.h.wp=function(a){var b=dW(this,a);if(b&&5!=b.Ge){try{this.Bq(a),a.cl()}catch(c){}eW(this,b)}};
_.h.fI=function(a){(a=dW(this,a))&&0==a.Ge&&(fW(this,a),a.Ge=1)};var fW=function(a,b){a.SA?(a=setTimeout((0,_.R)(function(){bW(b)||gW(this,b)},a),a.SA),b.Mk=a):gW(a,b)},gW=function(a,b){var c=a.JV-a.SA;0<c&&(a=setTimeout((0,_.R)(function(){bW(b)||(b.Ge=4,this.wp(b.Re))},a),c),b.Mk=a)},hW=function(a){null!=a.Mk&&(clearTimeout(a.Mk),a.Mk=null)};_.h=cW.prototype;_.h.eI=function(a){(a=dW(this,a))&&!bW(a)&&1==a.Ge&&(hW(a),a.Ge=3)};_.h.cI=function(a){(a=dW(this,a))&&!bW(a)&&(a.Nr=!1)};
_.h.aI=function(a){var b=dW(this,a);if(b&&!bW(b)){try{this.Bq(a)}catch(c){}eW(this,b)}};_.h.bI=function(a){(a=dW(this,a))&&!bW(a)&&(a.Ge=4,this.wp(a.Re))};_.h.dI=function(a,b){(a=dW(this,a))&&!bW(a)&&2<=b&&4>=b&&!bW(a)&&(hW(a),a.Ge=2)};var eW=function(a,b){hW(b);b.Ge=5;a=a.Rv;for(var c in a)a[c]==b&&delete a[c]},dW=function(a,b){return a.Rv[b.n]},iW=function(){this.Uc=window.gbar.wg};_.h=iW.prototype;_.h.mC=function(a,b,c){return this.Uc.rc(a,b,c)};_.h.nH=function(a,b){return this.Uc.fc(a,b)};
_.h.sD=function(a){this.Uc.sc(a)};_.h.Bq=function(a){this.Uc.hc(a)};_.h.wp=function(a){this.Uc.cc(a)};_.h.fI=function(a){this.Uc.os(a)};_.h.eI=function(a,b){this.Uc.or(a,b)};_.h.cI=function(a){this.Uc.oh(a)};_.h.aI=function(a){this.Uc.oc(a)};_.h.bI=function(a,b,c,d,e,f){this.Uc.oe(a,b,c,d,e,f)};_.h.dI=function(a,b,c,d){this.Uc.oi(a,b,c,d)};var jW=function(){cW.call(this)};_.K(jW,cW);
var kW=function(a){if(window.___jsl.man)a(window.___jsl.man);else{var b=function(){var d=new jW;window.___jsl.man=d;a(d)};if(window.gbar){var c=function(){if(window.gbar.wg){var d=new iW;window.___jsl.man=d;a(d)}else b()};window.gbar.wg?c():window.gbar.qm?window.gbar.qm(c):b()}else b()}},lW=function(){return window.___jsl.man};
var mW=function(a){this.qZ=a;a.then((0,_.R)(function(){},this),function(){},this)},nW=function(a,b){a.qZ.then(function(c){var d=c.startFeedback;if(!d)throw Error("eb`startFeedback");return d.apply(c,b)})},pW=function(a,b,c){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];e=oW(a,b).then(function(f){return f.apply(null,d)});return new mW(e)},qW={},oW=function(a,b){var c=qW[b];if(c)return c;c=(c=_.mi(b))?_.Hk(c):(new _.Dk(function(d,e){var f=(new _.Ld(document)).createElement("SCRIPT");
f.async=!0;_.kk(f,_.rd(a));f.onload=f.onreadystatechange=function(){f.readyState&&"loaded"!=f.readyState&&"complete"!=f.readyState||d()};f.onerror=e;(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){var d=_.mi(b);if(!d)throw Error("fb`"+b+"`"+a);return d});return qW[b]=c};
var rW=function(a){this.zW=a};rW.prototype.v_=function(a){nW(this.zW,arguments)};var sW=_.Qb("https://www.gstatic.com/feedback/js/help/prod/service/lazy.min.js");oW(sW,"help.service.Lazy.create").Xr(function(){});
var tW={contactid:!0,cdu:!0,cmp:!0,email:!0,hl:!0,n:!0,m:!0,p:!0,src:!0,userid:!0,sp:!0,ytid:!0};_.Eb({nm:!0,s:!0,pr:!0,v:!0},tW);
var uW=function(){this.Gq=_.Nk();this.Gq.promise.then(function(a){_.rr(a.Ma(),{border:"none","margin-bottom":"-4px"});_.rr(a.Bb(),{"border-radius":"4px",overflow:"hidden","box-shadow":"rgba(0, 0, 0, 0.3) 0px 4px 16px"})})};_.h=uW.prototype;_.h.OA=function(a){_.Tl.open(a,this.Gq.resolve)};_.h.FI=function(){this.Gq.promise.then(function(a){return a.close()})};_.h.NA=function(a,b,c,d){this.Gq.promise.then(function(e){return e.send(a,c,d,b)})};
_.h.MA=function(a,b,c){this.Gq.promise.then(function(d){return d.Yv({updateContainer:{visible:a,x:b,y:c}})})};_.h.Cj=function(a,b,c){_.Tl.Cj(a,c,b)};
var vW=/(?:^|\s)g-(?:hovercard|profile)(?:$|\s)/,wW={loadDelay:400,hoverDelay:500,closeDelay:500},xW=0,yW=function(a){return document.body==a?"body":a.__cardid||null},zW=function(a){var b=yW(a);b||(b=a.__cardid=xW++);return String(b)},AW=function(a){var b=a.className||"getAttribute"in a&&a.getAttribute("class");!(b=b&&vW.test(b))&&(b=a.getAttribute)&&(b=/-[a-z]/.test("hovercardId")?!1:_.mU&&a.dataset?"hovercardId"in a.dataset:a.hasAttribute?a.hasAttribute("data-"+_.lU("hovercardId")):!!a.getAttribute("data-"+
_.lU("hovercardId")));return b||"getAttribute"in a&&a.getAttribute("oid")&&36==_.S("card/p")?!0:"G:HOVERCARD"==a.tagName.toUpperCase()},BW=function(a,b){var c={};_.Eb(c,wW,_.S("iframes/card")||{},_.S("card")||{});for(var d=[],e=a;e;e=e.parentNode){var f=yW(e);f&&b[f]&&d.push(b[f])}_.nb(d.reverse(),function(g){_.Eb(c,g)});b="G:HOVERCARD"==a.tagName.toUpperCase()?"":"data-";d=a.attributes;for(e=0;e<d.length;e++)_.dd(d[e].name,b)&&(c[d[e].name.substring(b.length)]=d[e].value);"getAttribute"in a&&a.getAttribute("oid")&&
36==_.S("card/p")&&(c.ytid=a.getAttribute("oid"));!c.userid&&"A"==a.tagName.toUpperCase()&&a.pathname&&(b=a.pathname.match(/^\/?(\d+)$/),/\.google\.com$/.test(a.hostname)&&b&&(c.userid=b[1]));c.hl||(c.hl=_.S("lang")||_.Me.getUrlParameters().hl||void 0);c.m=c.entity;c.src=c.source;delete c.entity;delete c.source;return c},CW=function(a,b){b=b[a];"number"!==typeof b&&(b=wW[a]);return 0>b?0:b};
var DW=function(a){this.qp=a;this.Re=new _.pP(this);this.Ga=null;this.Ru=!1;this.nJ=0;this.lp=!1};_.h=DW.prototype;
_.h.load=function(a){$V(this.Ei);a=_.zx(a,function(f,g){return tW[g]&&null!=f});a.origin=window.location.protocol+"//"+window.location.host;var b=this,c=this.qp,d={_event:function(f){if(!(f.timestamp<c.gB)){if("sgcp_ams"==f.event)c.Nu=!0,c.ov=!1;else if(c.Nu&&"mouseover"==f.event)c.ov=!0;else if(c.Nu&&"mouseout"==f.event)c.ov=!1;else if("sgcp_amh"==f.event)c.Nu=!1,c.ov||EW(c);else{var g=!1;switch(f.event){case "calendar":g=c.ih.scheduleEventHandler;break;case "chat":g=c.ih.sendChatHandler;break;case "email":g=
c.ih.sendEmailHandler;break;case "feedback":g=c.ih.feedbackHandler;break;case "videoChat":g=c.ih.videoChatHandler}g&&g(c.ih["hovercard-id"]||c.ih.userid||c.ih.email)}if("mouseover"==f.event||"sgcp_ams"==f.event)window.clearTimeout(c.Ih),c.Ih=null;if(f.cpid){for(g=document.getElementById(f.cpid);g&&"BODY"!=g.parentNode.tagName;)g=g.parentNode;c.hB=g}f.fromCard&&"mouseout"==f.event&&EW(c)}},_ready:(0,_.R)(this.yd,this),version:function(f){c.Qe(c.mj,{type:"circles_changed",version:f.v})},loaded:function(f){f.ri==
b.nJ&&b.tW()},rendered:function(){var f=b.qp.Ul,g=_.Lq(document);b.lp&&(b.xj(!0,f.x+g.x,f.y+g.y),b.lp=!1,f=b.qp,f.Qe(f.mj,{type:"show",frame:b.Ga}))},renderfailed:function(){b.lp=!1;b.xj(!1,0,0)},disposed:function(){b.Ga.close()},cardAction:function(f){FW(c,f)}},e=":card";!_.S("iframes/card/url")&&_.S("iframes/hovercard/url")&&(e=":hovercard");a=_.lj(_.oj(_.nj(new _.jj({disableMultiLevelParentRelay:!0,hover:!0}),d),_.ym),a).Nd("hover").setUrl(e);_.S("card/relayOpenTop")&&(_.mj(a,-1),_.pj(a).NC("_default"));
_.Tl.open(a.value(),(0,_.R)(function(f){this.Ga=f;_.rr(f.Ma(),{border:"none","margin-bottom":"-4px"});_.rr(f.Bb(),{"border-radius":"4px",overflow:"hidden","box-shadow":"rgba(0, 0, 0, 0.3) 0px 4px 16px"})},this))};_.h.yd=function(){this.Ru=!0;this.xj(!1,0,0);this.Ei.yv({});var a=this.qp;a.Rd&&a.nB(a.Rd)};_.h.to=function(a){this.Ei=a};_.h.PS=function(a){this.Ga.send("getHealthc",void 0,a,_.ym)};_.h.IT=function(a,b){this.Ga.send("getVarc",a,b,_.ym)};
_.h.xj=function(a,b,c){this.Ga.updateContainer?this.Ga.updateContainer(a,b,c):this.Ga.Yv({updateContainer:{visible:a,x:b,y:c}})};_.h.show=function(){this.xj(!0,0,-1E4);this.Ga.send("render",void 0,void 0,_.ym);this.lp=!0};_.h.mc=function(){this.Ga.send("hide",void 0,void 0,_.ym);this.xj(!1,0,0);var a=this.qp;a.Qe(a.mj,{type:"hide"});a.mj=null;a.ih=null;this.lp=!1};_.h.close=function(){this.Ga.send("dispose",void 0,void 0,_.ym)};_.h.enable=function(){};_.h.disable=function(){};
var GW=function(){this.SJ=0;this.mA=[];this.Ai={};this.kt={};this.Xb={};this.gB=this.Ih=this.jg=this.Bn=this.ih=this.mj=this.uc=this.Rd=this.tf=null;this.Ul={x:0,y:0};this.ov=this.Nu=!1;this.hB=null;this.SF=new Map;_.mi("gapi.load")("gapi.iframes.style.slide-menu")},HW=function(a,b,c,d){var e=zW(b);e=a.Xb[e]||(a.Xb[e]={});e[c]||(e[c]=d=(0,_.R)(d,a),b.addEventListener?b.addEventListener(c,d,"focus"==c||"blur"==c):("focus"==c?c="focusin":"blur"==c&&(c="focusout"),b.attachEvent("on"+c,d)))},IW=function(a,
b,c){(a=a.Xb[zW(b)])&&a[c]&&(b.addEventListener?b.removeEventListener(c,a[c],"focus"==c||"blur"==c):b.detachEvent("focus"==c?"onfocusin":"blur"==c?"onfocusout":"on"+c,a[c]),delete a[c])},JW=function(a,b){var c=a.Xb[b.id];if(c)for(var d in c)c.hasOwnProperty(d)&&IW(a,b,d)};_.h=GW.prototype;
_.h.ms=function(a,b,c){if(a=a||document.body){this.SJ++;var d=zW(a);b&&(this.Ai[d]=b);c&&(this.kt[d]=c);HW(this,a,"mouseover",this.$H);HW(this,a,"mouseout",this.xA);HW(this,a,"mousedown",this.uu);HW(this,a,"focus",this.$H);HW(this,a,"blur",this.xA);HW(this,document.body,"mouseout",this.xA);HW(this,document.body,"mousedown",this.uu);c&&c.preload&&(b=this.Rd=document.createElement("div"),this.uc=BW(b,this.kt),KW(this))}else window.setTimeout((0,_.R)(this.ms,this),100)};
_.h.PD=function(a){if(a=a||document.body)if(EW(this,0),a!=document.body?JW(this,a):IW(this,document.body,"mouseover"),a=zW(a),delete this.Ai[a],delete this.kt[a],!(0<--this.SJ)){JW(this,document.body);var b=this.tf;this.HA();this.tf=null;window.setTimeout(function(){var c=lW();c&&b&&c.wp(b.Re)},100)}};_.h.Sd=function(a){this.mA.push(a)};_.h.fm=function(a){_.li(this.mA,a)};_.h.Qe=function(a,b){for(var c=[];a;){var d=yW(a);d&&this.Ai[d]&&c.push(this.Ai[d]);a=a.parentNode}_.He(c,this.mA);_.nb(c,function(e){e(b)})};
_.h.$H=function(a){this.gB=_.kb();var b=a.target||a.srcElement;if(b&&"IFRAME"!=b.tagName){for(;b&&!AW(b);)if(b=b.parentNode,!b||1!=b.nodeType)return;if(b)if(this.mj==b||this.Rd==b)this.Ih&&(window.clearTimeout(this.Ih),this.Ih=null);else{this.Rd=b;HW(this,b,"mousemove",this.zU);"focus"==a.type||"focusin"==a.type?(a=_.ns(b),this.Ul.x=a.x,this.Ul.y=a.y+b.offsetHeight):(this.Ul.x=a.clientX,this.Ul.y=a.clientY);this.Bn=_.kb();a=this.uc=BW(b,this.kt);var c=CW("hoverDelay",a);this.tf?this.tf.Ru&&(window.clearTimeout(this.jg),
this.jg=window.setTimeout((0,_.R)(this.nB,this,b),c-CW("loadDelay",a))):KW(this)}}};_.h.xA=function(a){this.gB=_.kb();if("blur"!=a.type||a.target==this.mj||a.target==this.Rd){if(a=a.relatedTarget||a.toElement){if("IFRAME"==a.tagName)return;if(this.hB)for(;a&&"BODY"!=a.tagName;){if(a==this.hB)return;a=a.parentNode}}EW(this)}};_.h.uu=function(){EW(this,0)};_.h.zU=function(a){this.Ul.x=a.clientX;this.Ul.y=a.clientY};
var KW=function(a){a.jg&&(window.clearTimeout(a.jg),a.jg=null);if(a.Rd&&(a.Qe(a.Rd,{type:"hover",config:a.uc}),!a.tf)){var b=a.tf=new DW(a);kW((0,_.R)(function(c){c.mC("card",LW++,b.Re)&&b.load(this.uc)},a))}};
GW.prototype.nB=function(a){this.jg&&(window.clearTimeout(this.jg),this.jg=null);if(this.Rd==a){var b=CW("hoverDelay",this.uc)-CW("loadDelay",this.uc)-_.kb()+this.Bn;if(0<b)this.jg=window.setTimeout((0,_.R)(this.nB,this,a),b);else{this.Qe(a,{type:"hover",config:this.uc});this.uc.feedbackHandler||(this.uc.feedbackHandler=this.w_);this.uc.overrideFeedback=!0;this.uc.scheduleEventHandler&&(this.uc.overrideCalendar=!0);this.uc.sendChatHandler&&(this.uc.overrideChat=!0);this.uc.sendEmailHandler&&(this.uc.overrideEmail=
!0);this.uc.videoChatHandler&&(this.uc.overrideVideoChat=!0);b=this.tf;var c=this.uc;a=(0,_.R)(this.fM,this,a);b.Ru&&(b.tW=a,c.ri=++b.nJ,b.Ga.send("loadData",c,void 0,_.ym))}}};
GW.prototype.w_=function(){var a={};a={apiKey:a.apiKey||a.apiKey,environment:a.i$||a.environment,helpCenterPath:a.S$||a.helpCenterPath,locale:a.locale||a.locale||"en".replace(/-/g,"_"),nonce:a.nonce||a.nonce,productData:a.productData||a.productData,receiverUri:a.vaa||a.receiverUri,renderApiUri:a.Daa||a.renderApiUri,theme:a.bba||a.theme,window:a.window||a.window};a=pW(sW,"help.service.Lazy.create","5003140",a);(new rW(a)).v_({productVersion:"gapi",customZIndex:2000000002})};
GW.prototype.fM=function(a){if(this.Rd===a&&this.tf&&this.tf.Ru&&this.Bn){var b=CW("hoverDelay",this.uc)-_.kb()+this.Bn;0<b?window.setTimeout((0,_.R)(this.fM,this,a),b):(this.HA(),this.mj=this.Rd,this.ih=this.uc,IW(this,this.Rd,"mousemove"),this.Bn=this.uc=this.Rd=null,lW().sD(this.tf.Re))}};
var EW=function(a,b){a.Rd&&IW(a,a.Rd,"mousemove");a.Rd=null;a.uc=null;a.Bn=null;a.jg&&(window.clearTimeout(a.jg),a.jg=null);!a.Ih&&a.mj&&(a.Ih=window.setTimeout((0,_.R)(a.HA,a),"number"===typeof b?b:CW("closeDelay",a.ih)))};GW.prototype.HA=function(){this.Ih&&(window.clearTimeout(this.Ih),this.Ih=null);this.mj&&lW().Bq(this.tf.Re)};var FW=function(a,b){a.Qe(null,b);a.XB&&a.XB.send("cardAction",b,void 0,a.WB)};
GW.prototype.my=function(a,b,c){var d={};d.frame=a;d.filter=b||_.um;d.callback=c||_.cb;this.SF.set(String(_.bd(a)),d);a.register("cardAction",(0,_.R)(function(e){FW(this,e);d.callback(e)},this),d.filter)};GW.prototype.oy=function(a){this.WB=a||_.um;_.Tl.Cj((0,_.R)(function(b){this.XB=b;this.XB.register("cardAction",(0,_.R)(this.Zs,this),this.WB)},this),void 0,this.WB)};
GW.prototype.Zs=function(a){this.SF.forEach(function(b){return b.frame.send("cardAction",a,void 0,b.filter)});this.tf&&this.tf.Ga.send("cardAction",a,void 0,_.ym)};var LW=0;
_.MW=function(){var a={},b=new GW,c=new uW;a.ms=function(d,e,f){b.ms(d,e,f)};a.PD=function(d){b.PD(d)};a.Sd=function(d){b.Sd(d)};a.fm=function(d){b.fm(d)};a.my=function(d,e,f){b.my(d,e,f)};a.oy=function(d){b.oy(d)};a.Zs=function(d){b.Zs(d)};a.wa=function(d,e){e.origin=window.location.protocol+"//"+window.location.host;var f=_.Tl.Rh({url:":card",where:document.getElementById(d),queryParams:e,messageHandlers:{_ready:function(){f.send("loadData",e,void 0,_.ym)},loaded:function(){f.send("render",void 0,
void 0,_.ym)}},messageHandlersFilter:_.ym})};a.FI=function(){c.FI()};a.MA=function(d,e,f){c.MA(d,e,f)};a.NA=function(d,e,f,g){c.NA(d,e,f,g)};a.OA=function(d){c.OA(d)};a.BV=function(d,e,f){c.Cj(d,e,f)};a.DV=function(){return _.ym};a.EV=function(){return _.um};return a}();
_.C("gapi.card.watch",_.MW.ms);_.C("gapi.card.unwatch",_.MW.PD);_.C("gapi.card.addCallback",_.MW.Sd);_.C("gapi.card.removeCallback",_.MW.fm);_.C("gapi.card.render",_.MW.wa);_.C("gapi.card.connectChild",_.MW.my);_.C("gapi.card.connectOpener",_.MW.oy);_.C("gapi.card.broadcast",_.MW.Zs);_.C("gapi.card.iframeClose",_.MW.close);_.C("gapi.card.iframeRestyle",_.MW.MA);_.C("gapi.card.iframeSend",_.MW.NA);_.C("gapi.card.iframeSetup",_.MW.OA);_.C("gapi.card.iframeAddOnOpenerHandler",_.MW.BV);
_.C("gapi.card.iframeGetCrossOriginFilter",_.MW.DV);_.C("gapi.card.iframeGetSameOriginFilter",_.MW.EV);

});
// Google Inc.
