/* JS */ gapi.loaded_5(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var BG=function(a,b,c,d,e){this.width=a;this.height=b;this.Fm=c;this.Gm=d;this.opacity=e},CG=function(a,b,c,d){return new BG(void 0==b?a.width:b,void 0==c?a.height:c,a.Fm,a.Gm,void 0==d?a.opacity:d)};BG.prototype.equals=function(a){return this.width==a.width&&this.height==a.height&&this.Fm==a.Fm&&this.Gm==a.Gm&&this.opacity==a.opacity};
BG.prototype.interpolate=function(a,b){var c=1-b;return new BG(Math.round(this.width*c+a.width*b),Math.round(this.height*c+a.height*b),Math.round(this.Fm*c+a.Fm*b),Math.round(this.Gm*c+a.Gm*b),this.opacity*c+a.opacity*b)};
_.DG=function(a){_.ps.call(this,a);this.ya=new _.js(this)};_.fi(_.DG,_.rs);_.h=_.DG.prototype;
_.h.create=function(){var a=Number(this.bk(200,"widgetWidth","width")),b=Number(this.bk(100,"widgetHeight","height")),c=this.bk("auto","corner"),d=this.bk({},"menuCss"),e=this.bk(!0,"hideOnClick");this.Cq=!!this.bk(!0,"hideOnLeave");this.SD=!!this.bk((0,_.bz)(),"useCss3Transition");this.pQ=!!this.bk(!0,"allowOffset");var f=document.createElement("div");this.Aa=f;var g=this.Ah();g.parentNode.appendChild(f);var k=document.createElement("div");this.Dm=k;f.appendChild(k);d.position="absolute";d.width=
a+"px";d.height="0";d.border=d.border||"1px solid #aaa";d.background=d.background||"#fff";d.zIndex=_.vs(this);d.overflow="hidden";d.boxShadow=d.MozBoxShadow=d.webkitBoxShadow=d.boxShadow||"0 2px 2px rgba(0,0,0,0.3)";_.rr(f,d);_.rr(k,{left:"-1000px",top:"-1000px",position:"absolute",width:a+"px",height:b+"px"});this.y0=f.offsetWidth-a;this.A0=f.offsetHeight;d="auto"==c?["top","start"]:c.split("-");g=_.Lr(g);this.Ys="bottom"==d[0];this.Zv="right"==d[1]||"left"!=d[1]&&g;this.Yg=EG(this,a,b,"auto"==c);
this.uD=_.y.setTimeout((0,_.R)(this.t_,this),500);this.ya.V(f,"mouseover",this.NB);this.ya.Rq(f,"mouseout",this.MB,!1,this);e&&_.y.setTimeout((0,_.R)(function(){this.yp||this.ya.V(document,"click",this.fX)},this),0)};
_.h.open=function(){this.create();this.ka.Lf(this.Aa);this.ka.Sd("resize",(0,_.R)(this.resize,this));this.ka.Pg("showMenu",(0,_.R)(this.gM,this));var a=this.ka.methods;a.setHideOnLeave=(0,_.R)(this.Dr,this);a.displayStateCallback&&(this.tG=a.displayStateCallback,delete a.displayStateCallback);this.ka.lg(this.Dm,{height:"100%"});_.FG(this,this.Yg)};
_.h.yd=function(a){this.yp||(a=a||{},this.Dm.style.left="0",this.Dm.style.top="0",this.qj&&(_.be(this.qj),this.qj=null),this.uD&&(_.y.clearTimeout(this.uD),this.uD=null),GG(this,parseInt(a.width,10)||parseInt(this.ka.width,10)||this.Yg.width,parseInt(a.height,10)||parseInt(this.ka.height,10)||this.Yg.height))};_.h.resize=function(a){this.yp||GG(this,isNaN(+a.width)?this.Yg.width:+a.width,isNaN(+a.height)?this.Yg.height:+a.height)};_.h.close=function(){this.GA?HG(this):(this.jy=!0,IG(this))};
_.h.bk=function(a,b){for(var c,d=1,e=arguments.length;d<e&&(c=this.ua[arguments[d]],void 0===c);++d);if(void 0!==c){if(c&&"object"==typeof c){d={};for(var f in c)d[f]=c[f];return d}return c}return a};
var EG=function(a,b,c,d){var e=a.Ah(),f=_.$r(e.offsetParent);f.right-=a.y0;f.bottom-=a.A0;if(d){var g=e.offsetLeft;d=g+b<f.right;g=g+e.offsetWidth-b>=f.left;a.Zv=a.Zv?!d||g:!d&&g;g=e.offsetTop;d=g+c<f.bottom;g=g+e.offsetHeight-c>=f.top;a.Ys=a.Ys?!d||g:!d&&g}d=a.pq(a.Zv,e.offsetLeft,e.offsetWidth,b,f.left,f.right);a=a.pq(a.Ys,e.offsetTop,e.offsetHeight,c,f.top,f.bottom);return new BG(b,c,d,a,1)};
_.DG.prototype.pq=function(a,b,c,d,e,f){return a?(a=b+c,Math.min(f-a,Math.max(e+d-a,0))):Math.max(e-b,Math.min(f-b-d,0))};var GG=function(a,b,c){a.ka.Ma().style.width=b+"px";a.ka.Ma().style.height=c+"px";a.Dm.style.width=b+"px";a.Dm.style.height=c+"px";b=a.pQ?EG(a,b,c,!1):CG(a.Az,b,c);a.Yg=b;a.qk||JG(a,b)};_.h=_.DG.prototype;_.h.Dr=function(a){this.Cq=!!a};_.h.NB=function(){!this.qk&&this.Ll&&(_.y.clearTimeout(this.Ll),this.Ll=null)};
_.h.MB=function(a){if(!(this.qk||this.Ll||!this.Cq||a.relatedTarget&&_.fe(this.Aa,a.relatedTarget))){var b=_.as(this.Aa);a=a.clientY>b.top&&a.clientY<b.top+b.height?0:300;this.Ll=_.y.setTimeout((0,_.R)(this.Dq,this),a)}};_.h.fX=function(a){_.us(this.Aa,a)||this.Dq()};_.h.gM=function(a){this.show(!!a||void 0===a)};_.h.show=function(a){a?this.xD():this.Dq()};_.h.xD=function(){!this.yp&&this.GA&&(this.qk=this.GA=!1,_.FG(this,this.Yg))};
_.FG=function(a,b){KG(a,CG(b,void 0,0,0));_.y.setTimeout((0,_.R)(function(){this.qk||(this.Yg=b,this.SD&&_.az(this.Aa,"width 350ms cubic-bezier(.23, .50, .32, 1),height 350ms cubic-bezier(.23, .50, .32, 1),left 350ms cubic-bezier(.23, .50, .32, 1),top 350ms cubic-bezier(.23, .50, .32, 1),opacity 350ms cubic-bezier(.23, .50, .32, 1)"),JG(this,b),this.ct(!0,!1),this.Lr&&(_.y.clearTimeout(this.Lr),this.jy=!1),this.Lr=_.y.setTimeout((0,_.R)(this.ct,this,!0,!0),350))},a),0)};
_.DG.prototype.Dq=function(){this.qk||IG(this)};
var IG=function(a){a.qk||(a.ct(!1,!1),JG(a,CG(a.Az,void 0,0,0)),a.qk=!0,a.Lr&&_.y.clearTimeout(a.Lr),a.Lr=_.y.setTimeout((0,_.R)(function(){this.GA=!0;this.jy?(HG(this),this.jy=!1):(this.SD&&_.az(this.Aa,""),this.Aa.visibility="hidden",this.Aa.left="-1000px",this.Aa.top="-1000px");this.ct(!1,!0)},a),350))},HG=function(a){a.yp=!0;_.qi(a.ya);a.ya=null;a.Ll&&(_.y.clearTimeout(a.Ll),a.Ll=null);a.Rm&&(_.y.clearTimeout(a.Rm),a.Rm=null);_.be(a.Aa);a.Aa=null;_.be(a.Ah());a.Dm=null;a.qj=null};
_.DG.prototype.ct=function(a,b){var c=this.tG;c&&_.y.setTimeout(function(){c(a,b)},0)};_.DG.prototype.t_=function(){this.qj=document.createElement("div");this.qj.style.width=this.qj.style.height="100%";this.qj.style.position="absolute";this.qj.style.background="url(//ssl.gstatic.com/ui/v1/activityindicator/loading_gs.gif) no-repeat "+(this.Yg.width-19)/2+"px "+(this.Yg.height-19)/2+"px";this.Aa.appendChild(this.qj)};
var JG=function(a,b){if(!a.qk)if(a.SD)KG(a,b);else{var c=_.kb()-20+350;a.Rm&&_.y.clearTimeout(a.Rm);a.NJ(a.Az,b,c)}},KG=function(a,b){var c=a.Aa,d=a.Ah();c.style.left=a.Zv?d.offsetLeft+d.offsetWidth+b.Fm-b.width+"px":d.offsetLeft+b.Fm+"px";c.style.width=b.width+"px";c.style.top=a.Ys?d.offsetTop+d.offsetHeight+b.Gm-b.height+"px":d.offsetTop+b.Gm+"px";c.style.height=b.height+"px";_.Ur(c,b.opacity);a.Az=b};
_.DG.prototype.NJ=function(a,b,c){this.Rm=null;if(!this.yp&&!a.equals(b)){var d=_.kb();d>=c?KG(this,b):(KG(this,a.interpolate(b,1-Math.pow(1-Math.min(1-(c-d)/350,1),3))),this.Rm=_.y.setTimeout((0,_.R)(this.NJ,this,a,b,c),20))}};_.DG.prototype.open=_.DG.prototype.open;_.DG.prototype.onready=_.DG.prototype.yd;_.DG.prototype.close=_.DG.prototype.close;

_.gm["slide-menu"]=function(a){var b=new _.DG(_.WT(a)),c=new _.As(b);b.open=function(){};b.create();a.attributes={height:"100%"};a.where=b.Dm;a.onClose=function(){b.close()};a.onRestyle=function(d){if(d){var e=!1;d.hasOwnProperty("showMenu")&&(b.gM(d.showMenu),e=!0);d.hasOwnProperty("setHideOnLeave")&&(b.Dr(d.setHideOnLeave),e=!0);e||b.resize(d)}};a.onCreate=function(d){d.Oc=function(){return this.iu("openerIframe")};c.ka=b.ka=d;d.Lf(b.Aa);d.register("_ready",(0,_.R)(b.yd,b),_.ym);b.tG=function(e,
f){!d.Mb&&d.fo([e,f])};_.FG(b,b.Yg);c.open()}};

});
// Google Inc.
